### ISSUE TITLE
print被重定向了吗？

### ISSUE THREAD

**Issue by zhicongchen** [letiantian/TextRank4ZH#13]
您好！这个包真的很棒！感谢！

不过，在我使用Jupyter Notebook调用这个包的时候，所有print的输出都被直接输出到terminal中了，而通常默认情况下都会输出到页面的cell output上，请问是不是在这个包里面设置了将print的内容重定向了？以及怎么改回来呢？

谢谢！

**Comment by letiantian** [comment]
并没有设置重定向

。源码里与print相关的只有：
```
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
```
以及`util.py`中的debug函数。

**Comment by MiHuMOOC** [comment]
请问你是如何改回来的？
