### ISSUE TITLE
可以用作英文吗？ 

### ISSUE THREAD

**Issue by meshiguge** [letiantian/TextRank4ZH#14]

**Comment by letiantian** [comment]
可以。但是 cat和Cat可能被认为是两个词。

**Comment by Sixoloy** [comment]
对全文进行分词的时候为何不采用并行，这样每句都能独立处理最后再进行归并。

**Comment by letiantian** [comment]
@Sixoloy 
这样看jieba分词的实现了。

1、如果要并行，用什么方式实现？多线程？多进程？
2、是该在分词阶段并行？还是处理大量文章时候并行？
3、文本数量不多，没必要并行。
4、纯CPU操作，单核CPU的话，有必要并行吗？

**Comment by Sixoloy** [comment]
我觉得可以像jieba那样添加并行的选项，当用到Segmentation分句的时候可以按照选项决定是否要每句开一个线程分词。这样用多核机器处理大量文章的时候还是会有性能提升的吧。

**Comment by letiantian** [comment]
也许会吧。 我更倾向于开多个进程和线程处理文章就行了。
