### ISSUE TITLE
Jupyter Notebook 中 print 无法显示

### ISSUE THREAD

**Issue by hscspring** [letiantian/TextRank4ZH#15]
rt  

打印结果全部显示在 Bash 窗口了，就是启动 `jupyter notebook` 的窗口……请问这个能解决吗？  
谢谢。

**Comment by letiantian** [comment]
自己动下源码吧。 参考下这个： http://stackoverflow.com/questions/25494182/print-not-showing-in-ipython-notebook-python

**Comment by hscspring** [comment]
非常感谢。  
我应该自己找答案的。  
正在把你的源码当做样板学习中。:smile: 👍
