### ISSUE TITLE
求问搜狗实体关系提取比赛数据集

### ISSUE THREAD

**Issue by tumiumiu** [letiantian/TextRank4ZH#17]
您好，我最近看到您关于搜狗实体关系提取比赛的笔记，想请问您这个比赛的数据集您还有保留吗，如果有的话能否发给我一份呢（shanyegouqiwang@163.com），感激不尽。

**Comment by tumiumiu** [comment]
抱歉在不相关的地方发了这个，因为实在没找到您的联系方式，请见谅。

**Comment by letiantian** [comment]
抱歉，已经没有了。😭
