### ISSUE TITLE
能够自定义停止词吗？

### ISSUE THREAD

**Issue by GuohyCoding** [letiantian/TextRank4ZH#24]
你好，TextRank4ZH实在是太棒了，学到了很多，请问能够自定义停止词吗？我目前用两种方法替换stopwords.txt好像都没有效果
1. tr4w.__init__(stop_words_file='./stopwords.txt') 初始化中指定stopwords.txt
2. E:\Anaconda3\Lib\site-packages\textrank4zh 在pip安装目录下替换stopwords.txt
但是结果好像想去除的词还是没有去除掉，请问该怎么做到自定义停止词呢？

**Comment by letiantian** [comment]
关键词提取的结果中不应该有停止词的。建议打断点定位下原因。

**Comment by waveb0** [comment]
> 你好，TextRank4ZH实在是太棒了，学到了很多，请问能够自定义停止词吗？我目前用两种方法替换stopwords.txt好像都没有效果
> 
> 1. tr4w.**init**(stop_words_file='./stopwords.txt') 初始化中指定stopwords.txt
> 2. E:\Anaconda3\Lib\site-packages\textrank4zh 在pip安装目录下替换stopwords.txt
>    但是结果好像想去除的词还是没有去除掉，请问该怎么做到自定义停止词呢？

您好，我也遇到了这个问题，请问您怎么解决能够实现自定义停止词的呢？
